# This is a basic workflow to help you get started with Actions

name: My-github

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
  
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: checkout repo content
         uses: actions/checkout@v1 # checkout the repository content to github runner.
       - name: setup python
         uses: actions/setup-python@v2
         with:
          python-version: 3.8 #install the python needed
       - name:  Install packages
         uses: BSFishy/pip-action@v1
         with: 
           packages:
            markdown
       - name: execute py script # run the run.py to get the latest data
         # run: python test.py
         run: python -m markdown README.md > foo.html
       - name: Commit report
         run: 
          git config --global user.name 'zkop'
          git config --global user.email 'zkop@mail.ru'
          git commit -am "Automated report"
          git push
        
        

  
     
       
